# Не понятно - как передавать - будто с диском работает!

# 1. txt
POST http://localhost:9191/pdftool/convertpdf
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="field-name"; filename="test.txt"

< ./test.txt
--WebAppBoundary--

###

# 2. pdf
POST http://localhost:9191/pdftool/convertpdf
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="field-name"; filename="test1.pdf"

< ./test1.pdf
--WebAppBoundary--

###

# 3. png
POST http://localhost:9191/pdftool/convertpdf
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="field-name"; filename="test.png"

< ./test.png
--WebAppBoundary--

###
