# 1. txt - Error!
POST http://localhost:9191/pdftool/compresspdf
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="field-name"; filename="test.txt"

< ./test.txt
--WebAppBoundary--

###

# 2. pdf - ???
POST http://localhost:9191/pdftool/compresspdf
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="field-name"; filename="test.pdf"

< ./test.pdf
--WebAppBoundary--

###

# 3. pdf - ???
POST http://localhost:9191/pdftool/compresspdf
Content-Type: application/pdf

< ./test1.pdf

###

### curl -X POST -H "content-type:application/pdf" -F "data=@./test1.pdf"  http://172.27.9.79:8088/pdftool/compresspdf --output res.pdf
POST http://172.27.9.79:8088/pdftool/compresspdf
Content-Type: application/pdf

< ./test1.pdf

###
